keys:
  - &rumtower age1qfyrgusnydn54uf343qarlwhlax8rx6dj3uuvkaafj3y3ckmzassh9m9kz
  - &rumprism age1za78rel729f9g0snme0nwm6xt6pza7kgv024wuh440j4v5yv8s3qpdqd5l
  - &rumnas age1ryjhgkrgaa0j2nep3333tpww42frkn6w2xqftljpawqtg6veusjsx4q79l
  - &saibaman age1ma7ee4v574nt4wu5g35c7qq5g93yx7zw96mzw8f6yp5dmdwdtq0s8ahp8s

creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *rumtower
        - *rumprism
        - *rumnas
  - path_regex: secrets/saibaman.yaml$
    key_groups:
      - age:
        - *saibaman
        - *rumtower
        - *rumnas
