{...}: {
  services.syncthing = {
    settings.devices = {
      rumbeta.id = "3FRVZJQ-RG6QI2E-B2WIQ4W-7MIJ2LB-ZCHLSI4-WQVTTUS-SRFAOUS-JUAEVAI";
      rumprism.id = "RVLPXSV-2XJT3ZJ-LNTRNRB-XQWY372-EPLFFPB-Z74FVM6-SVIYHRF-6777ZQ6";
      rumpixel.id = "3FRVZJQ-RG6QI2E-B2WIQ4W-7MIJ2LB-ZCHLSI4-WQVTTUS-SRFAOUS-JUAEVAI";
      rumtower.id = "VAMK7HO-ILEHTIX-P53VEG3-ZLDD4XO-AJEIP7J-WMBTQCS-GMEZSQD-YFYLZAQ";
      pixel7.id = "MSUJMBA-Y43BYQV-46UWP42-MILYJF7-NTPNIKQ-Y6I6BZ7-PGW4YPK-HCZGZQK";
    };
  };
}
