{...}: {
  services.syncthing = {
    settings.devices = {
      rumprism.id = "OLEKHRG-6BF7JZC-X4Y24UP-TECMIPV-3ZDRQCV-FLM2AUI-DGYJABL-XQK2KQJ";
      rumtower.id = "VAMK7HO-ILEHTIX-P53VEG3-ZLDD4XO-AJEIP7J-WMBTQCS-GMEZSQD-YFYLZAQ";
      pixel7.id = "MSUJMBA-Y43BYQV-46UWP42-MILYJF7-NTPNIKQ-Y6I6BZ7-PGW4YPK-HCZGZQK";
    };
  };
}
